---
- name: install consul server
  hosts: consul_server
  become: yes
  tasks:
  - name: install consul server and enable ui on port 8500
    copy: src=/etc/ansible/scripts/consul-server.sh dest=/home/ubuntu mode=0777
  - name: Execute the script
    shell: /home/ubuntu/consul-server.sh
    become: yes
